# Description:
#   Marketing Bullshit
#
# Dependencies:
#   None
#
# Configuration:
#   None
#
# Commands:
#   hubot bullshit me
#
# Author:
#   brantwynn
#     - mostly stolen from http://www.dack.com/web/bullshit.html

verbs = [
  "assemble"
  "aggregate"
  "architect"
  "automate"
  "benchmark"
  "brand"
  "blend"
  "build"
  "create"
  "curate"
  "converge"
  "cultivate"
  "customize"
  "deliver"
  "deploy"
  "develop"
  "disintermediate"
  "drive"
  "e-enable"
  "embrace"
  "empower"
  "enable"
  "engage"
  "engineer"
  "enhance"
  "envisioneer"
  "evolve"
  "expedite"
  "exploit"
  "extend"
  "facilitate"
  "generate"
  "grow"
  "harness"
  "implement"
  "incentivize"
  "incubate"
  "innovate"
  "inspire"
  "integrate"
  "iterate"
  "leverage"
  "matrix"
  "maximize"
  "mesh"
  "monetize"
  "morph"
  "optimize"
  "orchestrate"
  "personalize"
  "productize"
  "recontextualize"
  "redefine"
  "reintermediate"
  "reinvent"
  "repurpose"
  "revolutionize"
  "scale"
  "seize"
  "socialize"
  "strategize"
  "streamline"
  "syndicate"
  "synergize"
  "synthesize"
  "target"
  "transform"
  "transition"
  "unleash"
  "utilize"
  "visualize"
  "whiteboard"
]

adjectives = [
  "clicks-and-mortar"
  "value-added"
  "vertical"
  "proactive"
  "robust"
  "revolutionary"
  "scalable"
  "leading-edge"
  "innovative"
  "free"
  "intuitive"
  "strategic"
  "e-business"
  "mission-critical"
  "sticky"
  "one-to-one" 
  "24/7"
  "end-to-end"
  "global"
  "B2B"
  "B2C"
  "granular"
  "frictionless"
  "virtual"
  "virtuous"
  "viral"
  "dynamic"
  "24/365"
  "best-of-breed"
  "killer"
  "magnetic"
  "bleeding-edge"
  "web-enabled"
  "interactive"
  "dot-com"
  "sexy"
  "breakthrough"
  "evolved"
  "agile"
  "actionable"
  "relevant"
  "epic"
  "extreme"
  "amazing"
  "experimental"
  "simplified"
  "best-in-class"
  "back-end" 
  "real-time"
  "efficient"
  "front-end"
  "distributed"
  "seamless"
  "self-service"
  "extensible"
  "turn-key"
  "world-class" 
  "open-source"
  "cross-platform"
  "cross-media"
  "synergistic"
  "bricks-and-clicks"
  "out-of-the-box"
  "enterprise" 
  "enterprise-ready" 
  "enterprise-grade" 
  "integrated"
  "impactful"
  "digital"
  "wireless"
  "transparent"
  "next-generation"
  "cutting-edge"
  "user-centric"
  "visionary" 
  "customized"
  "ubiquitous"
  "plug-and-play"
  "collaborative"
  "compelling"
  "holistic"
  "rich"
  "immersive"
]

nouns = [
  "synergies"
  "web-readiness"
  "paradigms"
  "markets"
  "partnerships"
  "infrastructures"
  "platforms"
  "initiatives"
  "life-cycles"
  "channels"
  "eyeballs"
  "communities"
  "conversions"
  "ROI"
  "solutions"
  "e-tailers"
  "e-services"
  "action-items"
  "portals"
  "niches"
  "campaigns"
  "verticals"
  "technologies"
  "content"
  "vortals"
  "devops"
  "supply-chains"
  "convergence"
  "relationships"
  "architectures"
  "interfaces"
  "e-markets"
  "e-commerce"
  "systems"
  "bandwidth"
  "infomediaries"
  "models"
  "mindshare"
  "deliverables"
  "users"
  "schemas"
  "networks"
  "applications"
  "metrics"
  "e-business"
  "functionalities"
  "repositories"
  "toolkits"
  "products"
  "experiences"
  "web services"
  "methodologies"
]

conjunctions = [
  "and"
  "with"
  "for"
  "via"
  "because of"
  "in case of"
  "rather than"
  "alongside"
  "including"
  "coupled with"
  "in companion to"
  "in addition to"
  "among"
  "amidst"
  "surrounded by"
  "in the thick of"
  "integrating"
  "together with"
  "neck and neck with"
  "neighboring"
  "close to"
  "at the edge of"
  "verging on"
  "adjacent to"
  "opposed to"
  "juxtaposed with"
  "overlooking"
  "embedded into"
  "combined with"
  "next door to"
  "at the hand of"
  "through the agency of"
  "under the aegis of"
  "in competition with"
  "not to mention"
  "made up of"
  "plus"
  "supported by"
  "without compromising"
  "near"
  "situated on"
  "as a result of"
  "through the medium of"
  "with the help of"
  "by means of"
  "by virtue of"
  "per"
  "through"
  "driving"
  "while adopting"
]  

module.exports = (robot) ->
  robot.respond /bullshit me/i, (msg) ->
    ism = ""
    ism += msg.random verbs
    ism += " "
    ism += msg.random adjectives
    ism += " "
    ism += msg.random nouns
    ism += " "
    ism += msg.random conjunctions
    ism += " "
    ism += msg.random adjectives
    ism += " "
    ism += msg.random nouns
    msg.send ism
