# Description:
#   Marketing Bullshit
#
# Dependencies:
#   None
#
# Configuration:
#   None
#
# Commands:
#   hubot bullshit me
#
# Author:
#   brantwynn
#     - mostly stolen from http://www.dack.com/web/bullshit.html

verbs = [
  "assemble"
  "aggregate"
  "architect"
  "benchmark"
  "brand"
  "blend"
  "create"
  "curate"
  "cultivate"
  "deliver"
  "deploy"
  "disintermediate"
  "drive"
  "e-enable"
  "embrace"
  "empower"
  "enable"
  "engage"
  "engineer"
  "enhance"
  "envisioneer"
  "evolve"
  "expedite"
  "exploit"
  "extend"
  "facilitate"
  "generate"
  "grow"
  "harness"
  "implement"
  "incentivize"
  "incubate"
  "innovate"
  "integrate"
  "iterate"
  "leverage"
  "matrix"
  "maximize"
  "mesh"
  "monetize"
  "morph"
  "optimize"
  "orchestrate"
  "productize"
  "recontextualize"
  "redefine"
  "reintermediate"
  "reinvent"
  "repurpose"
  "revolutionize"
  "scale"
  "seize"
  "strategize"
  "streamline"
  "syndicate"
  "synergize"
  "synthesize"
  "target"
  "transform"
  "transition"
  "unleash"
  "utilize"
  "visualize"
  "whiteboard"
]

adjectives = [
  "clicks-and-mortar"
  "value-added"
  "vertical"
  "proactive"
  "robust"
  "revolutionary"
  "scalable"
  "leading-edge"
  "innovative"
  "intuitive"
  "strategic"
  "e-business"
  "mission-critical"
  "sticky"
  "one-to-one" 
  "24/7"
  "end-to-end"
  "global"
  "B2B"
  "B2C"
  "granular"
  "frictionless"
  "virtual"
  "viral"
  "dynamic"
  "24/365"
  "best-of-breed"
  "killer"
  "magnetic"
  "bleeding-edge"
  "web-enabled"
  "interactive"
  "dot-com"
  "sexy"
  "back-end" 
  "real-time"
  "efficient"
  "front-end"
  "distributed"
  "seamless"
  "extensible"
  "turn-key"
  "world-class" 
  "open-source"
  "cross-platform"
  "cross-media"
  "synergistic"
  "bricks-and-clicks"
  "out-of-the-box"
  "enterprise" 
  "enterprise-ready" 
  "enterprise-grade" 
  "integrated"
  "impactful"
  "digital"
  "wireless"
  "transparent"
  "next-generation"
  "cutting-edge"
  "user-centric"
  "visionary" 
  "customized"
  "ubiquitous"
  "plug-and-play"
  "collaborative"
  "compelling"
  "holistic"
  "rich"
]

nouns = [
  "synergies"
  "web-readiness"
  "paradigms"
  "markets"
  "partnerships"
  "infrastructures"
  "platforms"
  "initiatives"
  "life-cycles"
  "channels"
  "eyeballs"
  "communities"
  "ROI"
  "solutions"
  "e-tailers"
  "e-services"
  "action-items"
  "portals"
  "niches"
  "technologies"
  "content"
  "vortals"
  "supply-chains"
  "convergence"
  "relationships"
  "architectures"
  "interfaces"
  "e-markets"
  "e-commerce"
  "systems"
  "bandwidth"
  "infomediaries"
  "models"
  "mindshare"
  "deliverables"
  "users"
  "schemas"
  "networks"
  "applications"
  "metrics"
  "e-business"
  "functionalities"
  "experiences"
  "web services"
  "methodologies"
]

module.exports = (robot) ->
  robot.respond /bullshit me/i, (msg) ->
    ism = ""
    ism += msg.random verbs
    ism += " "
    ism += msg.random adjectives
    ism += " "
    ism += msg.random nouns
    msg.send ism
